### ISSUE TITLE
Listview inside tab bar?

### ISSUE THREAD

**Issue by josebalius** [brentvatne/react-native-scrollable-tab-view#122]
I am using a ListView inside one of my views, and I am noticing some conflicts with the ScrollView used by the tab view, sometimes I can see double scrollbars.

Question is, is there anything special you guys are doing to use ListViews inside this component?

**Comment by josebalius** [comment]
Also the scrolling is very yanky, I'm sure someone has done this already right?

**Comment by skv-headless** [comment]
Could you please make a screenshot?
Nothing special about ListView.
What do you mean by "yanky"?

**Comment by josebalius** [comment]
@skv-headless I'll get a screenshot today if I can (its hard to get them to show and stay there). In regards to yanky comment, I think the momentum scrolling from scrollview might be colliding with the momentum scrolling of the ListView that's why I was wondering if there was a proper way to use a ListView inside this component.

**Comment by grabbou** [comment]
I am getting good old `does not take rejections well, scrolling anyway` warnings with ListView.

**Comment by chenxiaohu** [comment]
+1
I am getting good old does not take rejections well, scrolling anyway warnings with ListView.

**Comment by ippy04** [comment]
+1 - getting "does not take rejection well, scrolling anyway warnings"

**Comment by grabbou** [comment]
@josebalius I've changed my component hierarchy and no longer getting that. Could you gist your render()?

**Comment by behl1** [comment]
@grabbou can you please explain what exactly you did to solve the error?

**Comment by jessezhang1986** [comment]
+1
I am getting good old does not take rejections well, scrolling anyway warnings with ListView.

**Comment by jessezhang1986** [comment]
+1
@grabbou  can you please explain what exactly you did to solve the error?

**Comment by grabbou** [comment]
Its' quite tricky since I am doing few apps at once and don't know which one I was referring to. Ping me on Discord with render() method content and I'll see what we can do ;)

**Comment by robin22333** [comment]
@grabbou 
```javascript
render() {
    return (
      <View style={{flex: 1}}>
        <ScrollableTabView>
          <View tabLabel='tab1' style={{flex: 1}}>
            <ListView
              style={{flex: 1}}
              dataSource={this.state.dataSource}
            />
          </View>
          <View tabLabel='tab2' style={{flex: 1}}>
            <ListView
              style={{flex: 1}}
              dataSource={this.state.dataSource}
            />
          </View>
        </ScrollableTabView>
      </View>
    )
  }
```
getting "does not take rejection well, scrolling anyway warnings"

**Comment by Emilios1995** [comment]
#174 This change solved the issue for me.

**Comment by robin22333** [comment]
@Emilios1995 thanks!!!

**Comment by skv-headless** [comment]
should be fixed in #174

**Comment by skleest** [comment]
Should this be reopened @skv-headless ? #174 doesn't seem to solve the issue and ListView momentum scroll does not work as intended.

**Comment by VladimirPal** [comment]
Why this issue is closed? It still not working and it's mean impossible to implement infinite scroll with ListView. I think you have to type about it on documentation.

**Comment by VladimirPal** [comment]
Why this issue is closed? It still not working and it's mean impossible to implement infinite scroll with ListView. I think you have to type about it on documentation.

**Comment by brookehurford** [comment]
I am having the "yanky" issue where my ListView is inside of the scrollable tab, and it is messing with the smooth scrolling of my ListView. It will only let me scroll to certain points on the screen and if I try to scroll to a specific area it pulls me up or down.

`<ScrollableTabView 
              tabBarBackgroundColor="white"
              tabBarUnderlineColor="#E51937"
              tabBarActiveTextColor="black"
              tabBarTextStyle={{fontSize: 14, paddingTop: 5}}>
                <ListView
                  tabLabel="List"
                  contentContainerStyle={styles.list}
                  ref="listview"
                  renderFooter={this._renderFooter}
                  initialListSize={15}
                  pageSize={15}
                  // onEndReached={this.loadMore}
                  // onEndReachedThreshold={1}
                  scrollRenderAheadDistance={10}
                  onScroll={this.onScroll}
                  dataSource={dataSource}
                  renderRow={this.renderPlace}
                  style={[styles.listView,styles.scrollContainer]}
                  />
                <View style={styles.flexContainer} tabLabel="Map">
                  {this.getMap()}
                </View>
            </ScrollableTabView>`

**Comment by hoangnm** [comment]
I got the same issue as @brookehurford.
