### ISSUE TITLE
Limited to only 5 Tab?

### ISSUE THREAD

**Issue by mafaik** [brentvatne/react-native-scrollable-tab-view#77]
I tried to create 7 scrollview tablabel, when i run it (android), it only display the first 5 tab. but when i swipe the content, i can view all the 7 content. Is there any wrong with the setting or the styles maybe?
Any answers would be appreciated, thanks

**Comment by pedramsaleh** [comment]
Do you mean that the first 5 tabs show, but there are more off screen that come on when you swype left?
I'm having an issue where if I put more tabs, they all squish up on the screen and are cut off.  I'd rather have them spread out, even if it means they go off screen.  I'm using the iOS version though.

**Comment by brentvatne** [comment]
You can implement this however you like with a custom tab bar, the default one doesn't include any kind of off-screen scrolling behavior and I don't have a need for it so I won't implement, but it would be cool for someone to submit a PR that implements this in a nice way as an alternate DefaultTabBar like DefaultTabBarScrollable :smile: :star:

**Comment by skv-headless** [comment]
We have scrollable tab bar, it is a little bit tricky. I think better to put it to examples to keep defaultTabBar simple. What do you think?

**Comment by avishayil** [comment]
I'm looking for an infinite scrolling tabbar as well. Any chance one of you guys familiar with?

**Comment by pedramsaleh** [comment]
There seem to be a few iOS solutions listed on this page, but they don't seem to be for React unfortunately.  
http://stackoverflow.com/questions/26260677/custom-scrollable-tab-bar-on-top-ios

I might have to get around to figuring out how to make this one do that if I can't find another solution, but I don't know when that will be.

**Comment by shukerullah** [comment]
Has anyone found a better solution to this issue?

**Comment by Belobobr** [comment]
We have such functionality  in our application. So.. https://github.com/brentvatne/react-native-scrollable-tab-view/pull/156

**Comment by skv-headless** [comment]
done in #156. Checkout hot to use in example. Later I'll update readme.

**Comment by pedramsaleh** [comment]
What version is this in?  I have 0.3.7 installed and still get the tabs all squished together and overlapping like before.

**Comment by skv-headless** [comment]
https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabsExample.js#L70
I'll update docs when I'll have time

**Comment by pedramsaleh** [comment]
That line you linked to didn't seem to have what I was looking for.  It was just an example of tab bar overlay.  I got it to work by using ScrollableTabBar.js from the PR to render my tab bar, instead of FacebookTabBar.js from the example.
